version: '3.9'

services:
    api:
        build:
            context: ./api
            dockerfile: Dockerfile
        restart: unless-stopped
        depends_on:
            - db
        volumes:
            - ./api:/srv/api:rw
        expose:
            - '9000'

    db:
        image: postgres:15
        restart: unless-stopped
        environment:
            POSTGRES_USER: translator
            POSTGRES_PASSWORD: 12345
            POSTGRES_DB: translator
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - db-data-psql:/var/lib/postgresql/data/pgdata:rw
        ports:
            - "5432:5432"

    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        environment:
            - NGINX_PORT=80
        restart: unless-stopped
        volumes:
            - ./api:/srv/api
        links:
            - api
        ports:
            - "80:80"

volumes:
    db-data-psql: { }
